#!/bin/sh

# --- Initialize -----------------------------------------------------
set -u
umask 0022
export LC_ALL=C
export PATH="$(command -p getconf PATH 2>/dev/null)${PATH+:}${PATH-}"
case $PATH in :*) PATH=${PATH#?};; esac
export UNIX_STD=2003  # to make HP-UX conform to POSIX

print_usage_exit() {
  cat <<-USAGE 1>&2
initial setup for migr

Usage   : ${0##*/} [options]
Options : -d <dir>|--dir=<dir>                Directory to store the migration
        : -h <host>|--host=<host>             Database host
        : -p <port>|--port=<port>             Database port
        : -d <dbname>|--dbname=<dbname>       Database name
        : -u <user>|--user=<user>             Database user
        : -p <password>|--password=<password> Database password
Version : 2024-05-02
USAGE
  exit 1
}

error_exit() {
  echo "${0##*/}: $1" 1>&2
  exit 1
}

# --- Parse Options --------------------------------------------------
case ${1:-} in -h|--help) print_usage_exit;; esac
cmd=$1
dir=migr
host=localhost
port=
dbname=
user=$(whoami)
password=password

case $cmd in
  psql)
    port=5432 ;;
  mysql)
    port=3306 ;;
  sqlite3) :  ;;
  *) error_exit "Unknown command: $cmd";;
esac
shift

while [ $# -gt 0 ]; do
  case $1 in
    --dir=*)       dir=${1#*=}     ; shift 1;;
    -h)            host=$2         ; shift 2;;
    --host=*)      host=${1#*=}    ; shift 1;;
    -p)            port=$2         ; shift 2;;
    --port=*)      port=${1#*=}    ; shift 1;;
    -d)            dbname=$2       ; shift 2;;
    --dbname=*)    dbname=${1#*=}  ; shift 1;;
    -u)            user=$2         ; shift 2;;
    --user=*)      user=${1#*=}    ; shift 1;;
    -w)            password=$2     ; shift 2;;
    --password=*)  password=${1#*=}; shift 1;;
    --) shift; break;;
    -*) echo "Unknown option: $1" 1>&2; exit 1;;
    *) break;;
  esac
done

[ -d "$dir" ] && error_exit "Directory already exists: $dir"

# --- Main -----------------------------------------------------------

# create a new directories and files
mkdir -p $dir

# Execute the initializtion sql
case $cmd in
  psql)
    [ -z "$host"     ] && error_exit "Host is not given."
    [ -z "$port"     ] && error_exit "Port is not given."
    [ -z "$dbname"   ] && error_exit "Database name is not given."
    [ -z "$user"     ] && error_exit "User is not given."
    [ -z "$password" ] && error_exit "Password is not given."
    PGPASSWORD=$password psql --host=$host --port=$port --dbname=$dbname --username=$user -c '
      CREATE TABLE IF NOT EXISTS migr (
        id         TEXT PRIMARY KEY,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    '
    ;;
  mysql)
    error_exit "Not implemented yet."
    ;;
  sqlite3)
    error_exit "Not implemented yet."
    ;;
  *)
    error_exit "Unknown command: $cmd";;
esac

[ $? -ne 0 ] && error_exit "Failed to create a table: migr"