#!/bin/sh

# --- Initialize -----------------------------------------------------
set -u
umask 0022
export LC_ALL=C
export PATH="$(command -p getconf PATH 2>/dev/null)${PATH+:}${PATH-}"
case $PATH in :*) PATH=${PATH#?};; esac
export UNIX_STD=2003  # to make HP-UX conform to POSIX

print_usage_exit() {
  cat <<-USAGE 1>&2
Usage   : ${0##*/} [options] <title>
Options : -d <dir>|--dir=<dir>        Directory to store the migration
Version : 2024-05-02
USAGE
  exit 1
}
error_exit() {
  echo "${0##*/}: $1" 1>&2
  exit 1
}

# --- Parse Options --------------------------------------------------
[ $# -eq 0 ] && print_usage_exit
case ${1:-} in -h|--help) print_usage_exit;; esac

dir=migr
while [ $# -gt 0 ]; do
  case $1 in
    -d)            dir=$2          ; shift 2;;
    --dir=*)       dir=${1#*=}     ; shift 1;;
    --) shift; break;;
    -*) echo "Unknown option: $1" 1>&2; exit 1;;
    *) break;;
  esac
done
title=$1

[ -z "$title" ] && error_exit "Title is not given."
[ -d "$dir"   ] || error_exit "Directory not found: $dir"

# --- Main -----------------------------------------------------------
# Create a new migration file's id
id=$(cat /dev/urandom     |
     tr -dc 'a-z0-9'      |
     fold -w 10           |
     head -n 1            )
tstamp=$(date '+%s')

# Check if the id is unique
find $dir -type f -name "*-$id-*.sql" |
wc -l                                 |
grep -q '^0$'                         ||
error_exit "Id collision: $id. Please try again."

# Validate the title
if [ "$title" != "$(printf "%s" "$title" | sed 's/[^a-z0-9_]//g;')" ]; then
  error_exit "Title is not valid. Only [a-z0-9_] are allowed."
fi

# Create a new migration file
new_up_file=$dir/$tstamp-$id-$title.up.sql
new_down_file=$dir/$tstamp-$id-$title.down.sql
touch "$new_up_file" "$new_down_file"
echo "Creating a new migration file: $new_up_file $new_down_file" 1>&2