#!/bin/sh

# --- Initialize -----------------------------------------------------
set -u
umask 0022
export LC_ALL=C
export PATH="$(command -p getconf PATH 2>/dev/null)${PATH+:}${PATH-}"
case $PATH in :*) PATH=${PATH#?};; esac
export UNIX_STD=2003  # to make HP-UX conform to POSIX

tmp=migr-test-$$
trap 'rm -rf $tmp' 0 1 2 3 15

ok() { echo "ok" ; }
ng() { echo "ng" ; exit 1 ; }

host=localhost
port=5432
dbname=test_migr
user=$(whoami)

# reset-table
PGPASSWORD=password \
psql  -U $user --host=localhost --port=5432 -d test_migr -c 'drop table migr;'

printf "Execute migr-init... "

./migr-init \
    psql \
    --dir=$tmp \
    --host=$host \
    --port=$port \
    --dbname=$dbname \
    --user=$user \
    --password=password 2>/dev/null 1>/dev/null

[ $? -eq 1 ] || ng ; ok

printf "Checking if the table migr exists in the database... "

count=$(PGPASSWORD=password psql \
    -Atq \
    -U $user \
    --host=$host \
    --port=$port \
    -d $dbname \
    -c 'SELECT count(*) FROM information_schema.tables WHERE table_name = '\''migr'\'';' )

[ $count -eq 1 ] || ng ; ok


printf "Checking if the table migr has the columns id, is_applied and created_at... "

count=$(PGPASSWORD=password psql \
    -Atq \
    -U $user \
    --host=$host \
    --port=$port \
    -d $dbname \
    -c 'SELECT count(*) FROM information_schema.columns WHERE table_name = '\''migr'\'' AND column_name = '\''id'\'';' )

[ $count -eq 1 ] || ng


count=$(PGPASSWORD=password psql \
    -Atq \
    -U $user \
    --host=$host \
    --port=$port \
    -d $dbname \
    -c 'SELECT count(*) FROM information_schema.columns WHERE table_name = '\''migr'\'' AND column_name = '\''is_applied'\'';' )

[ $count -eq 1 ] || ng

count=$(PGPASSWORD=password psql \
    -Atq \
    -U $user \
    --host=$host \
    --port=$port \
    -d $dbname \
    -c 'SELECT count(*) FROM information_schema.columns WHERE table_name = '\''migr'\'' AND column_name = '\''created_at'\'';' )

[ $count -eq 1 ] || ng ; ok


printf "Checking if the directory $tmp exists... "

[ -d $tmp ] || ng ; ok